version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Amazon Corretto 17..."
      - yum install -y java-17-amazon-corretto-devel
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - echo "Installing dependencies..."
      - chmod +x gradlew
  build:
    commands:
      - echo "Building Spring Boot app without tests..."
      - ./gradlew clean build -x test
artifacts:
  files:
    - build/libs/*.jar
